In [ ]:
#Q1
import numpy as np

In [ ]:
#Trignometric_Functions
print(np.rad2deg(30))
print(np.deg2rad(30))

print(np.radians(30))
print(np.degrees(30))

print(np.arctan2([1., -1.], [0., 0.]))
print(np.hypot(3,4))

1718.8733853924696
0.5235987755982988
0.5235987755982988
1718.8733853924696
[ 1.57079633 -1.57079633]
5.0


In [ ]:
#Hyperbolic_Functions
print(np.arcsinh(30))
print(np.arccosh(30))
print(np.arctanh(10))


4.09462222433053
4.0940666686320855
nan


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in arctanh
  after removing the cwd from sys.path.


In [ ]:
#Rounding
print(np.floor(3.5))
print(np.ceil(3.4))
print(np.trunc(3.5))

3.0
4.0
3.0


In [ ]:
#Sums_products_differences
print(np.trapz([5,4,3]))
print(np.cross([5,4,3],[1,2,3]))
print(np.gradient([5,4,3]))
print(np.ediff1d([5,4,3]))
print(np.diff([5,4,3]))
print(np.nancumsum([5,4,3]))
print(np.nancumprod([5,4,3]))

8.0
[  6 -12   6]
[-1. -1. -1.]
[-1 -1]
[-1 -1]
[ 5  9 12]
[ 5 20 60]


In [ ]:
#Exponents_logarithms
print(np.log2([0, 3, 2, 7]))
print(np.log1p([0, 3, 2, 7]))
print(np.logaddexp(3,4))
print(np.logaddexp2(5,4))
      

[      -inf 1.5849625  1.         2.80735492]
[0.         1.38629436 1.09861229 2.07944154]
4.313261687518223
5.584962500721156


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log2
  


In [ ]:
#Other_special_functions
print(np.sinc(5))



3.898171832519376e-17


In [ ]:
#Floating_point_routines
print(np.ldexp(2,3))
print(np.spacing(5))
print(np.nextafter(2,3))

16.0
8.881784197001252e-16
2.0000000000000004


In [ ]:
#Rational_routines
print(np.gcd(2,3))


1


In [ ]:
#Arithmetic_operations
print(np.divmod(2,3))
print(np.remainder(2,3))
print(np.modf(2))
print(np.mod(2,3))
print(np.fmod(2,7))

(0, 2)
2
(0.0, 2.0)
2
2


In [ ]:
#Handling_complex_numbers
print(np.conj(2))
print(np.conjugate(7))


2
7


In [ ]:
#Miscellaneous
print(np.maximum([0, 3, 2, 7],[5,4,8,6]))
print(np.minimum([0, 3, 2, 7],[5,4,8,6]))
print(np.fmax([0, 3, 2, 7],[5,4,8,6]))
print(np.fmin([0, 3, 2, 7],[5,4,8,6]))
print(np.interp([0, 3, 2, 7],[4,5],[8,9]))


[5 4 8 7]
[0 3 2 6]
[5 4 8 7]
[0 3 2 6]
[8. 8. 8. 9.]


In [ ]:
#Q2
#VStack
a = np.array([[1, 2, 3],[4,5,6]])
b = np.array([[4, 5, 6],[7,8,9]])
np.vstack((a,b))


array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#dStack
a = np.array([[1, 2, 3],[4,5,6]])
b = np.array([[4, 5, 6],[7,8,9]])
np.dstack((a,b))

array([[[1, 4],
        [2, 5],
        [3, 6]],

       [[4, 7],
        [5, 8],
        [6, 9]]])