In [1]:
# Classwork
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x_multi=[[0,1],[5,1],[15,2],[25,5],[35,11],[45,15],[55,34],[60,35]]

In [3]:
y=[4,5,20,14,32,22,38,43]

In [4]:
x_multi,y=np.array(x_multi),np.array(y)

In [5]:
print(x_multi)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]


In [6]:
print(y)

[ 4  5 20 14 32 22 38 43]


In [7]:
model=LinearRegression().fit(x_multi,y)

In [8]:
R_square=model.score(x_multi,y)
R_square

0.8615939258756775

In [9]:
print('theta 0',model.intercept_)
print('theta 1',model.coef_)

theta 0 5.52257927519819
theta 1 [0.44706965 0.25502548]


In [11]:
x_test_multi=np.array([[1,2]])
y_pred_multi=model.predict(x_test_multi)
y_pred_multi

array([6.47969989])

## Practice Multivariable regeression

In [12]:
import pandas as pd

Stock_Market = {'Year': [2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016],
                'Month': [12, 11,10,9,8,7,6,5,4,3,2,1,12,11,10,9,8,7,6,5,4,3,2,1],
                'Interest_Rate': [2.75,2.5,2.5,2.5,2.5,2.5,2.5,2.25,2.25,2.25,2,2,2,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75],
                'Unemployment_Rate': [5.3,5.3,5.3,5.3,5.4,5.6,5.5,5.5,5.5,5.6,5.7,5.9,6,5.9,5.8,6.1,6.2,6.1,6.1,6.1,5.9,6.2,6.2,6.1],
                'Stock_Index_Price': [1464,1394,1357,1293,1256,1254,1234,1195,1159,1167,1130,1075,1047,965,943,958,971,949,884,866,876,822,704,719]        
                }

df = pd.DataFrame(Stock_Market,columns=['Year','Month','Interest_Rate','Unemployment_Rate','Stock_Index_Price']) 

df

Year  Month  Interest_Rate  Unemployment_Rate  Stock_Index_Price
0   2017     12           2.75                5.3               1464
1   2017     11           2.50                5.3               1394
2   2017     10           2.50                5.3               1357
3   2017      9           2.50                5.3               1293
4   2017      8           2.50                5.4               1256
5   2017      7           2.50                5.6               1254
6   2017      6           2.50                5.5               1234
7   2017      5           2.25                5.5               1195
8   2017      4           2.25                5.5               1159
9   2017      3           2.25                5.6               1167
10  2017      2           2.00                5.7               1130
11  2017      1           2.00                5.9               1075
12  2016     12           2.00                6.0               1047
13  2016     11           1.75                5.9                965
14  2016     10           1.75                5.8                943
15  2016      9           1.75                6.1                958
16  2016      8           1.75                6.2                971
17  2016      7           1.75                6.1                949
18  2016      6           1.75                6.1                884
19  2016      5           1.75                6.1                866
20  2016      4           1.75                5.9                876
21  2016      3           1.75                6.2                822
22  2016      2           1.75                6.2                704
23  2016      1           1.75                6.1                719

In [13]:
from sklearn import linear_model

In [14]:
X = df[['Interest_Rate','Unemployment_Rate']]
y = df['Stock_Index_Price']
 

regr = linear_model.LinearRegression()
regr.fit(X, y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)



Intercept: 
 1798.403977625855
Coefficients: 
 [ 345.54008701 -250.14657137]


In [15]:
regr.score(X,y)

0.8976335894170215

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=109)

In [18]:
regr.fit(X, y)

LinearRegression()

In [19]:
y_pred=regr.predict(X_test)
print(y_pred)

[ 988.60472343 1200.06303087  877.20504454  952.24901595 1200.06303087
  877.20504454  927.23435881  877.20504454]


In [20]:
print(y_test)

12    1047
7     1195
19     866
14     943
8     1159
17     949
20     876
23     719
Name: Stock_Index_Price, dtype: int64
